# Site settings
title: Giovannini
email: giovannini.thomas@gmail.com
description: Yo, je développe des trucs
baseurl: ""
articles:
  - baseurl: /article/
url: "https://giovannini.github.io"

author:
  name     : 'Thomas Giovannini'
  email    : giovannini.thomas@gmail.com
  url      : https://giovannini.github.io
  linkedin : https://fr.linkedin.com/in/giovanninithomas
  twitter  : http://twitter.com/_giovannini
  github   : https://github.com/Giovannini

github: https://github.com/Giovannini
disqus_shortname: "giovannini"

paginate: 5
comments: true
paginate_path: "/page/:num"

plugins:
  - jekyll-paginate
  - jekyll-gist

whitelist:
  - jekyll-gist

sass:
  style: :compressed
  sass_dir: _sass

# Build settings
markdown  : kramdown
permalink : /article/:title

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
